version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: falatu_database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - app

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app

networks:
  app:
    name: "rede-app"
