version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: falatu_database
    ports:
      - "3308:3306"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
